import React from "react";
import Head from "next/head";

const Header = () => {
  return (
    <>
      <Head>
        <title>Disney game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="App-header my-10">
        <h1 className="text-6xl text-center">Disney Film and TV game</h1>
      </header>
    </>
  );
};

export default Header;
